
service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1


functions:
  rss-reader:
    handler: app/rss-reader/handler.hello
    events:
      - schedule: rate(24 hours)

  audio-transcoder:
    handler: app/audio-transcoder/handler.hello
    events:
    - stream:
        type: dynamodb
        arn:
          Fn::GetAtt:
            - Article
            - StreamArn
        batchSize: 1

resources:
  Resources:
    ServerlessXkeDemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-xke-demo
    Article:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: article
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  Outputs:
     NewOutput:
       Description: "Description for the output"
       Value: "Some output value"




#AWS_PROFILE=mchaaben serverless invoke local --function audio-transcoder
#AWS_PROFILE=mchaaben serverless invoke local --function rss-reader
#AWS_PROFILE=mchaaben serverless deploy -v
#SLS_DEBUG=* AWS_PROFILE=mchaaben serverless invoke local --function audio-transcoder --path ../event.json -v
