
service: aws-nodejs # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs8.10


functions:
  hello:
    handler: app/handler.hello
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - Article
              - StreamArn
          batchSize: 1
resources:
  Resources:
    ServerlessXkeDemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-xke-demo
    Article:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: article
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
#    ArticleStream:
#      Type: AWS::Lambda::EventSourceMapping
#      Properties:
#        BatchSize: 1
#        Enabled: True
#        EventSourceArn:
#          Fn::GetAtt: [ Article , StreamArn ]
#        FunctionName:
#          Fn::GetAtt: [ hello , Arn ]
#        StartingPosition: LATEST
  Outputs:
     NewOutput:
       Description: "Description for the output"
       Value: "Some output value"




#AWS_PROFILE=mchaaben serverless invoke local --function hello
#AWS_PROFILE=mchaaben serverless deploy -v
